Esmax/Models/Capacitacion/PregTests.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Esmax.Models.Capacitacion
{
    public class PregTests
    {
        public int id_test { get; set; }

        public string descripcion { get; set; }
        
        [Key]
        public string id_pregunta { get; set; }

        public string a { get; set; }
        
        public string b { get; set; }
        
        public string c { get; set; }
        
        public string d { get; set; }
        
        public string e { get; set; }
        
        public string correcta { get; set; }
    }
}

Esmax/Models/Capacitacion/ResultadosTest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Esmax.Models.Capacitacion
{
    public class ResultadosTest
    {
        [Key]
        public int id_resultado { get; set; }

        public string id_user { get; set; }

        public int id_test { get; set; }

        public string resp1 { get; set; }
        
        public string resp2 { get; set; }

        public string resp3 { get; set; }

        public string resp4 { get; set; }

        public string resp5 { get; set; }

        public string resp6 { get; set; }

        public string resp7 { get; set; }

        public string resp8 { get; set; }

        public string resp9 { get; set; }

        public string resp10 { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}", ApplyFormatInEditMode =true)]
        public DateTime? fecha_test_tomado { get; set; }

        public bool aprobado { get; set; }





    }
}

Esmax/Models/Capacitacion/Tests.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Esmax.Models.Capacitacion
{
    public class Tests
    {
        [Key] 
        public int id_test { get; set; }

        public string nombre { get; set; }

        public string estado { get; set; }

        public virtual ICollection<PregTests> PregTests { get; set; }

        public virtual ICollection<ResultadosTest> ResultadosTests { get; set; }

    }
}

Esmax/Controllers/CapacitacionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI.WebControls.Expressions;
using Esmax.Models;
using Esmax.Models.Capacitacion;
using Microsoft.Ajax.Utilities;

namespace Esmax.Controllers
{
    public class resultados
    {
        public string mensaje;
        public string aprobacion;
        public string estado;
        public int IdTest;
    }

    public class alternativa
    {
        public string resp;
    }

    
    
    public class CapacitacionController : Controller
    {
        
      
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET
        public ActionResult Index()
        {
            ViewBag.idDeshabilitado = 0;
            return View("SelecCapacitacion", "_Layout");
        }

        [HttpGet]
        [Authorize]
        public JsonResult validarRol(string id)
        {
            int nivel;
            int miId = int.Parse(id);
            var rol = (from au in db.Users where au.Id.Equals(id) select au.area_id).FirstOrDefault();
            var adm = (from au in db.Users where au.Id.Equals(id) select au.Rol).FirstOrDefault();
            var area = (from ar in db.Areas where ar.area_id == rol select ar.responsable_id).FirstOrDefault();

            
            if (id.Equals(area))
            {
                nivel = 2;
            }
            else
            {
                nivel = 3;
            }
            if (adm.Equals("Administrador"))
            {
                nivel = 1;
            }

            ViewBag.nivelUsuario = nivel;
            
            return Json(nivel, JsonRequestBehavior.AllowGet);

        }

        public ActionResult ResultadosMisTests()
        {
            return View("Resultados", "_Layout");
        }

        public ActionResult SeleccionarTest()
        {
            return View("SelecCapacitacion", "_Layout");
        }

        public ActionResult ResultadosGenerales()
        {
            return View("ResultadosGenerales", "_Layout");
        }

        public ActionResult CrearTest()
        {
            return View("CrearTest", "_Layout");
        }

        public ActionResult GraficasTest()
        {
            return  View("GraficosCapacitaciones", "_Layout");
        }
        
        [HttpGet]
        [Authorize]
        public JsonResult GetTests()
        {
            var lista = (from t in db.Tests where t.estado.Equals("Habilitado") select t).ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public JsonResult GetTestHabilitar()
        {
            var lista = (from t in db.Tests where t.estado.Equals("Deshabilitado") select t).ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }
        
        

        [HttpGet]
        [Authorize]
        public JsonResult GetResultados(string id_user)
        {
            var lista = (from r in db.ResultadosTests   where r.id_user.Equals(id_user) 
                select new {ID = r.id_resultado ,TEST= (from t in db.Tests where t.id_test == r.id_test select t.nombre), 
                 ESTADO = (r.aprobado == true ? "Aprobado":"Reprobado"), 
                 FECHA=r.fecha_test_tomado.Value.Day +" /"+ r.fecha_test_tomado.Value.Month +" /"+r.fecha_test_tomado.Value.Year
                 + "  " + r.fecha_test_tomado.Value.Hour + ":" + r.fecha_test_tomado.Value.Minute
                }).ToList();

            
            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public JsonResult GetResultadosGenerales()
        {
            var lista = (from r in db.ResultadosTests 
                select new {EVALUADO= (from u in db.Users where u.Id.Equals(r.id_user) select u.UserName),ID = r.id_resultado ,TEST= (from t in db.Tests where t.id_test == r.id_test select t.nombre), 
                    ESTADO = (r.aprobado == true ? "Aprobado":"Reprobado"), 
                    FECHA=r.fecha_test_tomado.Value.Day +" /"+ r.fecha_test_tomado.Value.Month +" /"+r.fecha_test_tomado.Value.Year
                          + "  " + r.fecha_test_tomado.Value.Hour + ":" + r.fecha_test_tomado.Value.Minute
                }).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }


        public ActionResult getDetalleResultado(int id)
        {
            int id_test = (from t in db.ResultadosTests where t.id_resultado == id select t.id_test).FirstOrDefault();
            ViewBag.idTestDetalle = id_test;
            ViewBag.id_detalle = id;
            
            return View("DetalleResultado", "_Layout");
        }


        [HttpGet]
        [Authorize]
        public JsonResult GetInfoResultado(int id)
        {
            ResultadosTest res = (from r in db.ResultadosTests where r.id_resultado == id select r).FirstOrDefault();
            var respuestas = (from t in db.PregTests where t.id_test == res.id_test select t).ToList();
            int correctas = 0;
            string aprobado = "";
            int porcentaje = 0;

            for (int i = 0; i < respuestas.Count; i++)
            {
                if (i + 1 == 1)
                {
                    if (res.resp1 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 2)
                {
                    if (res.resp2 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 3)
                {
                    if (res.resp3 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 4)
                {
                    if (res.resp4 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 5)
                {
                    if (res.resp5 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 6)
                {
                    if (res.resp6 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 7)
                {
                    if (res.resp7 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 8)
                {
                    if (res.resp8 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 9)
                {
                    if (res.resp9 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
                if (i + 1 == 10)
                {
                    if (res.resp10 == respuestas[i].correcta)
                    {
                        correctas++;
                    }
                }
            }
            porcentaje = ((correctas * 100) / respuestas.Count);
            if (respuestas.Count <= 4 && porcentaje == 75)
            {
                porcentaje = 80;
            }
            
            
            resultados miRes = new resultados();

            miRes.IdTest = res.id_test;
            miRes.mensaje = "Ha respondido correctamente " + correctas + " de " + respuestas.Count +
                          " preguntas"; 
            miRes.aprobacion = "Su porcentaje de aprobación es de: " + porcentaje + "%";
            if (res.aprobado)
            {
                miRes.estado = "Aprobado";
            }
            else
            {
                miRes.estado = "Reprobado";
            }
            
            Console.WriteLine("RES: " + miRes.mensaje);
            Console.WriteLine("RES: " + miRes.aprobacion);
            Console.WriteLine("RES: " + miRes.estado);
            Console.WriteLine("RES: " + miRes.IdTest);

            
            return Json(miRes, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public JsonResult getIdTest(int id_res)
        {
            int id = (from t in db.ResultadosTests where t.id_resultado == id_res select t.id_test).FirstOrDefault();
            
            return Json(id, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public JsonResult GetMisAlternativas(int id_res)
        {
            ResultadosTest id = (from t in db.ResultadosTests where t.id_resultado == id_res select t).FirstOrDefault();
            int total = (from t in db.PregTests where t.id_test == id.id_test select t).Count();
            List<alternativa> alts = new List<alternativa>();
            
            
            for (int i = 0; i < total; i++)
            {
                alternativa alt = new alternativa();
                if (i + 1 == 1)
                {
                    alt.resp = id.resp1;
                }
                if (i + 1 == 2)
                {
                    alt.resp = id.resp2;
                }
                if (i + 1 == 3)
                {
                    alt.resp = id.resp3;
                }
                if (i + 1 == 4)
                {
                    alt.resp = id.resp4;
                }
                if (i + 1 == 5)
                {
                    alt.resp = id.resp5;
                }
                if (i + 1 == 6)
                {
                    alt.resp = id.resp6;
                }
                if (i + 1 == 7)

Esmax/Views/Capacitacion/Capacitacion.cshtml
@using Microsoft.AspNet.Identity

@{
	ViewBag.Title = "Realizar Test";
	Layout = "../Shared/_Layout.cshtml";
}

@section styles
{
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
	<style>
		.accordion > .card:first-of-type {
			border-bottom: 1px; 
			border-bottom-right-radius: 0;
			border-bottom-left-radius: 0;
		}
		.accordion > .card .card-header {
			margin-bottom: 0px;
		}
	</style>
	<style>
       .radio {
         margin: 16px 0;
         display: block;
         cursor: pointer;
       }
       .radio input {
         display: none;
       }
       .radio input + span {
         line-height: 22px;
         height: 22px;
         padding-left: 22px;
         display: block;
         position: relative;
       }
       .radio input + span:not(:empty) {
         padding-left: 30px;
       }
       .radio input + span:before, .radio input + span:after {
         content: "";
         width: 22px;
         height: 22px;
         display: block;
         border-radius: 50%;
         left: 0;
         top: 0;
         position: absolute;
       }
       .radio input + span:before {
         background: #B4B2EE;
         transition: background 0.2s ease, -webkit-transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 2);
         transition: background 0.2s ease, transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 2);
         transition: background 0.2s ease, transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 2), -webkit-transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 2);
       }
       .radio input + span:after {
         background: #fff;
         -webkit-transform: scale(0.78);
                 transform: scale(0.78);
         transition: -webkit-transform 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.4);
         transition: transform 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.4);
         transition: transform 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.4), -webkit-transform 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.4);
       }
       .radio input:checked + span:before {
         -webkit-transform: scale(1.04);
                 transform: scale(1.04);
         background: #25237B;
       }
       .radio input:checked + span:after {
         -webkit-transform: scale(0.4);
                 transform: scale(0.4);
         transition: -webkit-transform 0.3s ease;
         transition: transform 0.3s ease;
         transition: transform 0.3s ease, -webkit-transform 0.3s ease;
       }
       .radio:hover input + span:before {
         -webkit-transform: scale(0.92);
                 transform: scale(0.92);
       }
       .radio:hover input + span:after {
         -webkit-transform: scale(0.74);
                 transform: scale(0.74);
       }
       .radio:hover input:checked + span:after {
         -webkit-transform: scale(0.4);
                 transform: scale(0.4);
       }
       
    </style>
}

<div class="container">
	<div class="row justify-content-center m-3">
		<div class="col-lg-12 col-sm-offset-2"> 

			<div class="wizard-container">
				<div class="card wizard-card" data-color="blue" id="wizard">
					
					<div class="wizard-header">
						<h3 style="align-content: center" class="wizard-title" v-if="finalizado === false">
							Responder Test
						</h3>
						<h3 v-else>
							Resultados
						</h3>
					</div>
					<div class="tab-content" v-if="finalizado === false">
						@RenderPage("partials/PreguntasCap.cshtml")

					</div>
					<div class="tab-content" v-else>
						@RenderPage("partials/ResultadosCap.cshtml")
					</div>
						
				</div>
			</div>
		</div>
	</div>
</div>



@section scripts
{
	<script>
	
		var preg = new Vue({
			el: '#app',
			
			data() {
				return {
					misPreguntas: [],
					user: null,
					id_test: @ViewBag.id_test,
					misRespuestas: [],
					pregunta:[],
					indice: 0,
					totalPreguntas:0,
					aprobadas:0,
					resultado: null,
					finalizado: false,
					casiFinalizado: false,
					porcentajeAprobacion:0
					
				}
			},
			
			mounted(){
				this.getPreguntas();
			},
			methods:{
				
				getPreguntas() {
					
					var urlPreg = "@Url.Action("GetPreguntas", "Capacitacion")";
					
					axios.get(urlPreg, 
						{params:{id:this.id_test}}
					).then(
							response => {this.misPreguntas = response.data;}).catch(error=>{console.log("error: " + error);}
					);
					
					var urlCantidad = "@Url.Action("GetCantidad","Capacitacion")";
					
						axios.get(urlCantidad, 
							{params:{id_test:this.id_test}}
						).then(
								response=>{this.totalPreguntas = response.data;}).catch(error=>{console.log("error: " + error);}
					);
					
					this.cargarPregunta();
				},
				
				getOrPost(){
					if(document.getElementById("radioA").checked == true || document.getElementById("radioB").checked == true || document.getElementById("radioC").checked == true || 
						document.getElementById("radioD").checked == true || document.getElementById("radioE").checked == true){
						var context = this;
                        					
							console.log((this.indice+1) + " vez que pasa por getOrPost");
							
								if(document.getElementById("radioA").checked == true){
									context.misRespuestas[context.indice]="a";
								}else if(document.getElementById("radioB").checked == true){
									context.misRespuestas[context.indice]="b";
								}else if(document.getElementById("radioC").checked == true){
									context.misRespuestas[context.indice]="c";
								}else if(document.getElementById("radioD").checked == true){
									context.misRespuestas[context.indice]="d";
								}else if(document.getElementById("radioE").checked == true){
									context.misRespuestas[context.indice]="e";
								}
								
								document.getElementById("radioA").checked = false;
								document.getElementById("radioB").checked = false;
								document.getElementById("radioC").checked = false;
								document.getElementById("radioD").checked = false;
								document.getElementById("radioE").checked = false;
								
								this.indice++;
								
								if(context.indice == (context.totalPreguntas-1)){
									context.casiFinalizado = true;
								}
								
								if(context.indice == context.totalPreguntas){
									context.finalizado = true;
									context.finalizarTest();
								}else{
									var urlPregunta = "@Url.Action("GetUnaPregunta","Capacitacion")";
									
									context.pregunta = context.misPreguntas[context.indice];
								}
					}else{
						console.log("Debe seleccionar una respuesta");
					}
					
					
					
				},
				
				cargarPregunta(){
					
					var context = this;
					
					var urlPregunta = "@Url.Action("GetUnaPregunta","Capacitacion")";
                    																						
					axios.get(urlPregunta, 
							{params:{id_test:context.id_test, index_pregunta:context.indice}}
					).then(
							response=>{context.pregunta = response.data;}).catch(error=>{console.log("error: " + error);}
					);
					
				},
				
				finalizarTest(){
					
					var id = this.id_test;
					
					var data = {
						respuestas: this.misRespuestas,
						id_test: id,
						id_user: @User.Identity.GetUserId(),
						total: this.totalPreguntas
					};
					
					
					var urlResp = "@Url.Action("obtenerResultado","Capacitacion")";
					
					
					axios.post(urlResp, data).then(
							response=>{this.resultado = response.data;}).catch(error=>{console.log("error: " + error);}
					);
					
					
				},
				getPreguntaAnterior(){
					var context = this;
					
					context.indice--;
					
					var respuesta = this.misRespuestas[this.indice];
					
					
					var urlPregunta = "@Url.Action("GetUnaPregunta","Capacitacion")";
																											
					axios.get(urlPregunta, 
							{params:{id_test:context.id_test, index_pregunta:context.indice}}
					).then(
							response=>{context.pregunta = response.data;}).catch(error=>{console.log("error: " + error);}
					);
					
					context.casiFinalizado = false;
					
					if(respuesta === "a"){
						document.getElementById("radioA").checked = true;
					}else if(respuesta === "b"){
						document.getElementById("radioB").checked = true;
					}else if(respuesta === "c"){
						document.getElementById("radioC").checked = true;
					}else if(respuesta === "d"){
						document.getElementById("radioD").checked = true;
					}else if(respuesta === "e"){
						document.getElementById("radioE").checked = true;
					}
					
					
				},
				
				volverSelecionarTest(){
					window.location.assign("@Url.Action("volverSeleccionar","Capacitacion")");
				}
				
				
			}
			
			
		});
			</script>}

Esmax/Views/Capacitacion/DetalleResultado.cshtml
@using Microsoft.AspNet.Identity

@{
	ViewBag.Title = "Resultados Test";
	Layout = "../Shared/_Layout.cshtml";
}

<br/>
<br/>
<center>
    <i v-if="info.estado === 'Aprobado'" class="fa fa-check fa-2x mr-2" style="color: #00b0ff"></i>
    <i v-if="info.estado === 'Reprobado'" class="fa fa-times fa-2x mr-2" style="color: red"></i>
</center>
    <br/>
<div class="row">
	<div class="col-sm-2">
            
	</div>
	<div class="col-sm-8">
		<h4 v-if="info.estado === 'Aprobado'" style="color: #00b0ff">Estado de test: {{info.estado}}</h4>
		<h4 v-if="info.estado === 'Reprobado'" style="color: red">Estado de test: {{info.estado}}</h4>
		<h5>{{info.mensaje}}</h5>
		<h5>{{info.aprobacion}}</h5>

		<br/>
		<hr/>
		<div v-for="pregunta, i in preguntas">
            <div v-if="respuestas[i].resp === pregunta.correcta" style="color: green">
                <i class="fa fa-check fa-2x mr-2"></i> {{pregunta.descripcion}}<br/>
                
            </div>
            <div v-else style="color: red">
                <i class="fa fa-times fa-2x mr-2"></i> {{pregunta.descripcion}}
            </div>
        </div>
		<hr/>
	</div>
	
        
	
</div>
<div class="row">
	<div class="col-sm-1">
	</div>
	<div class="col-sm-4">
		<input type="submit" style="float: right; width: 75%" v-on:click="volverMisResultados" class="btn btn-primary" value="Ver mis resultados"/>
	</div>
	<div class="col-sm-2">
    		
    </div>
	<div class="col-sm-4">
    	<input v-if="nivel != 3" type="submit" style="float: left; width: 75%" v-on:click="volverGenerales" class="btn btn-primary" value="Ver resultados generales"/>
    </div>
	<div class="col-sm-1">
    		
    </div>
</div>
<br/>
<br/>



@section scripts
{
	
	<script>
		var preg = new Vue({
			el: '#app',
			
			data() {
				return {
					id: @ViewBag.id_detalle,
					id_test: @ViewBag.idTestDetalle,
					info: null,
					preguntas:[],
					respuestas:[],
					nivel:0,
					id_user:'@User.Identity.GetUserId()'
				}
			},
			mounted(){
				this.getInfo();
			},
			methods:{
				
				getInfo(){
					var urlUserRol = '@Url.Action("validarRol", "Capacitacion")'; 
					axios.get(urlUserRol, 
						{params:{id:this.id_user}}
					).then(
						response => { this.nivel =response.data; }).catch(error => { console.log("error: " + error);
					});
					
					
					var urlInfo = '@Url.Action("GetInfoResultado", "Capacitacion")'; 
					axios.get(urlInfo, 
						{params:{id:this.id}}
					).then(
						response => { this.info =response.data; }).catch(error => { console.log("error: " + error);
					});
					
					this.getPreguntas();
				},
				
				getPreguntas(){
					var urlPreguntas = '@Url.Action("GetPreguntas", "Capacitacion")'; 
					axios.get(urlPreguntas, 
						{params:{id:this.id_test}}
					).then(
						response => { this.preguntas =response.data; }).catch(error => { console.log("error: " + error);
					});
					
					this.getRespuestas();
				},
				
				getRespuestas(){
					var urlRespuestas = '@Url.Action("GetMisAlternativas", "Capacitacion")'; 
					axios.get(urlRespuestas, 
						{params:{id_res:this.id}}
					).then(
						response => { this.respuestas =response.data; }).catch(error => { console.log("error: " + error);
					});
				},
				
				volverMisResultados(){
					window.location.assign("@Url.Action("ResultadosMisTests","Capacitacion")");
				},
				volverGenerales(){
					window.location.assign("@Url.Action("ResultadosGenerales","Capacitacion")");
				}
			}
		})
				
			</script>
	}